production:
    classname:    org.postgresql.Driver
    subprotocol:  postgresql
    host:         localhost
    database:     caribou_development
    user:         postgres

development:
    classname:    org.postgresql.Driver
    subprotocol:  postgresql
    host:         localhost
    database:     caribou_development_dev
    user:         postgres

test:
    classname:    org.postgresql.Driver
    subprotocol:  postgresql
    host:         localhost
    database:     caribou_development_test
    user:         postgres


